version: '3.8'

services:
  # Your Go Application
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=budget_tracker
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=budget_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: